# Sets the maximum line length. Code will be wrapped beyond this length.
max_width = 100

# Use spaces for indentation rather than tabs.
hard_tabs = false

# Configure the visual indentation of arguments and parameters.
fn_params_layout = "Compressed"

# Controls whether to put `else` on a new line.
newline_style = "Auto"
