# General
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
width = 80
max_width = 100
error_on_line_overflow = true
error_on_unformatted = true

# Comments
wrap_comments = true
format_code_in_doc_comments = true

# Control Flow
fn_call_width = 60
brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"

# Indentation
indent_style = "Block"
match_block_trailing_comma = true

# Imports
imports_indent = "Block"
imports_layout = "Vertical"
merge_imports = true

# Ordering
reorder_imports = true
reorder_modules = true

# Spaces
spaces_around_ranges = true
spaces_within_angle_brackets = true
spaces_within_parens_and_brackets = true

# Misc
use_try_shorthand = true
use_field_init_shorthand = true
normalize_comments = true
normalize_doc_attributes = true
